print("Informe dois números para que possa ser realizado as dieferentes formas de operação:")
print('O primeiro número:')
a = int(input())
print('O segundo número:')
b = int(input())

print(f'Soma de {a + b} é:')
print(f'Subtração de {a - b} é:')
print(f'Multiplicação de {a * b} é:')
print(f'Divisão de {a / b} é:')